#!/usr/bin/env python
import sys, re
from subprocess import check_output

commit_msg_filepath = sys.argv[1]


branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()
print (branch.decode("utf-8"))

# Edit this regex to change what branch name you want to match
# By default it will match issues such as W-123456
# So for example, if my branch name is something/W-123456
# and you do "git commit -m "My cool message"
# your commit message will be "W-123456 My cool message"
regex = '(W.\d+)'
if re.search(regex, branch.decode("utf-8")):
    issue = re.search(regex, branch.decode("utf-8")).group()
    with open(commit_msg_filepath, 'r+') as fh:
        commit_msg = fh.read()
        fh.seek(0, 0)
        fh.write('%s %s' % (issue, commit_msg))

